name: Spellcraft
main: io.github.harryprotist.Spellcraft
version: 0.01
commands:
 spellCraftRunning:
  description: is Spellcraft running?
 mana:
  description: manage your mana!
  aliases: m
 setmana:
  description: set mana
  default: op
 mload:
  description: load mana of current player
 msave:
  description: set mana of current player
